#!/bin/bash

BATTERY_INFO=$(acpi -b | grep "Battery 0")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')


# Full and short texts
if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "Battery:${BATTERY_POWER}%+"
  echo "⚡:${BATTERY_POWER}%+"
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo "Battery:${BATTERY_POWER}%-"
  echo "⚡:${BATTERY_POWER}%-"
else
  echo "Batery:${BATTERY_POWER}%"
  echo "⚡:${BATTERY_POWER}%"
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
