#!/bin/bash

BATTERY_INFO=$(acpi -b | grep "Battery 0")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -E -o '[0-9][0-9]?%')


if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "${BATTERY_POWER}+"
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo "${BATTERY_POWER}-"
else
  echo "${BATTERY_POWER}"
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
